Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [116]:
import numpy as np

n = int(input())
a_array = np.arange(n)[::-1]

list(a_array)

 8


[7, 6, 5, 4, 3, 2, 1, 0]

Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [118]:
# Берем N как n из пользовательского ввода выше.

b_array = np.arange(n+1)[::-1]
b_diagonal = np.diag(b_array)
b_matrix = np.matrix(b_diagonal)

print(b_matrix)
print(np.trace(b_matrix))

[[8 0 0 0 0 0 0 0 0]
 [0 7 0 0 0 0 0 0 0]
 [0 0 6 0 0 0 0 0 0]
 [0 0 0 5 0 0 0 0 0]
 [0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0]]
36


Задание 3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [119]:
left_coef = np.array( [ [4, 2, 1], [1, 3, 0], [5, 0, 4] ] )
right_coef = np.array( [4, 12, -3] )

from numpy import linalg

print(linalg.solve(left_coef, right_coef))
print(np.allclose(np.dot(left_coef, linalg.solve(left_coef, right_coef)), right_coef))

[-1.56  4.52  1.2 ]
True


Задание 4
Найдите самого похожего пользователя. Т.е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats.

In [129]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

next_user_stats = np.array([0, 1, 2, 0, 0, 0])
    
    
    
# Функции

def vector_length(a):
    
    a_length = np.linalg.norm(a)
    
    return a_length


def cos_similarity(a, b):
    
    cos_similarity = np.dot(a, b) / (vector_length(a) * vector_length(b))

    return cos_similarity



# Основной код

enumerated_dict = {}

for i, user_stats in enumerate(users_stats):
    enumerated_dict[i+1] = cos_similarity(next_user_stats, user_stats)
    
print(enumerated_dict)

print(f'User_id: {max(enumerated_dict, key=enumerated_dict.get)}, Similarity: {max(enumerated_dict.values())}')

{1: 0.19999999999999996, 2: 0.3999999999999999, 3: 0.7905694150420948, 4: 0.3999999999999999, 5: 0.0, 6: 0.0, 7: 0.9486832980505138, 8: 0.0, 9: 0.0}
User_id: 7, Similarity: 0.9486832980505138
